name: mycel_iam_mobile
description: Mycel IAM - mobile module
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  mycel_core_mobile:
    git:
      url: https://github.com/mycelpf/mycel_core.git
      ref: v0.1.0
      path: mycel_core_mobile
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
